name: "MagicMirror² (develop) and MMM-Pir build Testing"

on: [pull_request]

jobs:
  build:
    name: Test install MMM-Pir
    runs-on: ubuntu-latest
    steps:
      - name: "Use Node.js v20.x (latest)"
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          check-latest: true

      - name: Checkout MagicMirror² (develop)
        uses: actions/checkout@v4
        with:
          repository: MagicMirrorOrg/MagicMirror
          ref: develop

      - name: Install MagicMirror²
        run: npm install

      - name: Checkout MMM-Pir
        uses: actions/checkout@v4
        with:
          path: MagicMirror/modules/MMM-Pir

      - name: Install MMM-Pir
        run: npm run setup
        working-directory: MagicMirror/modules/MMM-Pir
        continue-on-error: false
